name: Check pods
on:
#  schedule:
#    - cron: '*/5 * * * *'
  push:
    branches:
      - 'master'

jobs:
  check:
    env:
      result_file: result.log
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        proxy_host: ${{secrets.JUMP_IP}}
        proxy_username: ${{ secrets.JUMP_USERNAME }}
        proxy_password: ${{ secrets.JUMP_PASS}}
        username: root
        host: 192.168.203.1
        password: QwertY_13  
        script: ls -l

    - name: Add 
      run: |
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        echo "$SSH_PRIVATE" > ~/.ssh/k3s
        sudo chmod 600 ~/.ssh/k3s
        ssh-add - <<< "$SSH_PRIVATE"
        echo "$SSH_PUB" > ~/.ssh/k3s.pub
        sudo chmod 600 ~/.ssh/k3s.pub
        sudo ssh-copy-id -i $SSH_KEY_PATH ${{secrets.JUMP_USERNAME}}@${{secrets.JUMP_IP}}
        ssh-keyscan -H 178.124.206.53 >> ~/.ssh/known_hosts
        sudo apt-get install sshuttle
        sshuttle -r ${{secrets.JUMP_USERNAME}}@${{secrets.JUMP_IP}} 192.168.0.0/16 &
      shell: bash
      env:
        SSH_PRIVATE: ${{secrets.SSH_PRIVATE}}
        SSH_PUBLIC: ${{secrets.SSH_PUB}}
        SSH_KEY_PATH: ~/.ssh/k3s.pub
    
    - name: Get kubectl
      uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{ secrets.KUBE_CONFIG }}
    
    - name: Check pods statuses  
      run: | 
        kubectl get pods -A >> ${{ env.result_file }}

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        path: ${{ env.result_file}} 
