name: Find tabs and changed files

on:
  pull-request:
    branches:
        - dev
        - features/do_one
        - hotfix/we_gonna_die
        - master

jobs:
  prepare:
    runs-on: self-hosted

    steps:
      - name: Get changed files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
    
      - name: Count tabs in changed files
        run: |
           for file in ${{ steps.changed-files.outputs.changed_files }}; do
             echo "$file was changed"
             echo "Count of tabs in ${file} is $(grep -c $'\t' ${file})" >> result.log
           done
    
      - name: Upload report
        uses: actions/upload-artifact@v3
        with:
          path: result.log
  


slack:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: git-test
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Post Content :rocket:'
        SLACK_TITLE: 'Looks like job is done :)'
        SLACK_USERNAME: Andrei Baitov
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
