name: Check remote host and push report

on:
  push:
    branches:
        - dev
        - features/do_one
        - hotfix/we_gonna_die
        - master

jobs:
  prepare:
    runs-on: self-hosted
      
    steps:
      - name: Install netcat
        run: sudo apt update && sudo apt install -y netcat
      - run: echo "netcat has been installed"
      - run: |
          nc -z -v -w2 onliner.by 443 > nc_report.log 2>&1
          touch /tmp/file.log
          ls -la
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          path: nc_report.log
